### ISSUE TITLE
Fork a thread

### ISSUE THREAD

**Issue by numeroteca** [numeroteca/pageonex#163]
This new feature would make possible to fork a thread to help remix and reuse!

The goal of this new feature is multiple:
- Making the life easier for researchers that want to use the same newspapers (order) and topics (colors, description, order). Now you need to create a thread and step by step add the newspapers, topics...
- Allowing users to reuse existing coding areas to work on them and add new topics, erase them...

What does it need to be copied to the new thread when forked?
The topics, media_threadx .... check data model section https://github.com/numeroteca/pageonex/wiki#data-model
Collaborators and owner are not copied to the new thread.

Highlighted areas will remain with the same owner but they will be duplicated. Note: if user modifies the area the are will continue to be owned by the original user.

The new forked thread should link to the parent thread below the title: "This thread has been forked from xxxx thread by yyyyy".

It has a similar behaviour of remixing in the Scratch project.

**Comment by xuanxu** [comment]
@numeroteca right now uniqueness is required for the name of the thread, so when forking we must change the name of the new thread. 
The easy solution is to add a random number 
(so a _panama-papers_ fork is named _panama-papers-23145_)
What do you think?

**Comment by numeroteca** [comment]
I think that's good. Maybe easier and simpler... would sequential numbers work?  _panama-papers-2_. That's what wordpress does for duplicated url.

**Comment by xuanxu** [comment]
I like the sequencial number, it is more elegant but it is not an easier solution in terms of code, because we need to track the number of forks already created by all users.

**Comment by numeroteca** [comment]
Then, let's go with the random number.
